# Generated by Django 2.1.5 on 2019-02-13 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.CharField(max_length=100)),
                ('Posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Posted_by', models.CharField(max_length=100)),
                ('Komentar', models.CharField(max_length=100)),
                ('Judul', models.CharField(max_length=100)),
                ('Isi', models.TextField(max_length=1000)),
            ],
        ),
    ]
