# Generated by Django 2.1.5 on 2019-02-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Foto',
            field=models.FileField(null=True, upload_to='blog/', verbose_name=''),
        ),
    ]
