# Generated by Django 2.1.5 on 2019-02-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.CharField(max_length=100)),
                ('Nama', models.CharField(max_length=100)),
                ('Slogan', models.TextField(max_length=100)),
            ],
        ),
    ]
